In [1]:
! ls

04_iwamoto_2011_Analyse.ipynb	04_iwamoto_2011_clinical.csv  taka_2011.pdf
04_iwamoto_2011_Analyse.pdf	04_iwamoto_2011_gex.csv       Untitled.ipynb
04_iwamoto_2011_Analysis_files	04_iwamoto_2011_merge.xlsx
04_iwamoto_2011_Analysis.html	GSE22093.xlsx

In [3]:
import pandas as pd
df = pd.read_excel('GSE22093.xlsx', skiprows=80,engine='openpyxl', index_col=0)
df.head()

,GSM549230,GSM549231,GSM549232,GSM549233,GSM549234,GSM549235,GSM549236,GSM549237,GSM549238,GSM549239,...,GSM750745,GSM750746,GSM750747,GSM750748,GSM750749,GSM750750,GSM750751,GSM750752,GSM750753,GSM750754
patient_ID,,,,,,,,,,,,,,,,,,,,,
1007_s_at,11.656917,11.041608,12.569615,12.283743,11.954910,11.346717,10.708971,11.974445,11.987945,11.895960,...,11.822675,11.683941,12.355737,11.631897,12.507083,11.611106,12.699856,12.290762,13.011281,11.533060
1053_at,8.922276,7.645466,8.994505,8.073775,9.288642,8.488596,8.419631,8.548015,9.672984,7.479526,...,8.727669,8.755989,7.577325,8.602348,7.356931,8.314332,7.676670,9.254762,7.932777,7.960109
117_at,7.804426,8.405843,8.111465,8.268126,8.088217,7.879945,9.022433,7.913748,7.230985,8.278296,...,7.841110,8.077391,7.510625,8.037592,7.640438,8.890462,7.973614,8.973624,8.278267,8.477482
121_at,10.262535,10.574645,10.699021,10.718334,10.351885,10.397266,10.299554,10.663488,10.477249,10.153529,...,10.124638,10.362445,10.638349,10.319471,10.918134,11.446473,10.885665,10.612086,11.180098,11.102243
1255_g_at,6.568635,6.436035,6.463451,6.794077,6.356024,5.589475,7.300213,5.984576,6.681168,5.995690,...,5.803980,6.215759,6.877894,6.865612,7.274050,7.907536,7.051468,6.244379,6.694349,4.215434

In [4]:
df.shape

(22284, 103)

In [5]:
df = df.T

In [6]:
df.drop('!series_matrix_table_end', axis=1, inplace=True)

In [7]:
df.reset_index(inplace=True)

In [8]:
df.rename(columns={'index':'patient_ID'}, inplace=True)

In [9]:
df.head(2)

patient_ID,patient_ID,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-5_at,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,GSM549230,11.656917,8.922276,7.804426,10.262535,6.568635,9.547638,7.792220,6.969494,10.506671,...,7.828237,9.697663,15.663557,15.31085,4.182382,3.840668,5.555082,1.228357,3.174974,2.647459
1,GSM549231,11.041608,7.645466,8.405843,10.574645,6.436035,9.926036,7.900622,5.775705,11.106255,...,6.032792,9.107146,15.558262,15.13942,4.874678,3.930106,5.390815,2.791853,5.114391,2.826359

In [10]:
cd = pd.read_csv('04_iwamoto_2011_clinical.csv')
cd.shape

(103, 12)

In [11]:
cd.head(3)

,patient_ID,FNA biopsy,RECIST,tp53 status,ER statut by geneExp,ER statut by IHC,age,prechemo t,prechemo tumor size,prechemo n,grade,NeoAdj_drug
0,GSM549230,pre-treatment,pCR,MUT,ERneg,ERneg,55.0,3.0,prechemo tumor size: NA,NaN,3.0,5-Fluorouracil/Doxorubicin/Cyclophosphamide
1,GSM549231,pre-treatment,pCR,WT,ERneg,ERneg,52.0,3.0,prechemo tumor size: NA,NaN,3.0,6-Fluorouracil/Doxorubicin/Cyclophosphamide
2,GSM549232,pre-treatment,pCR,MUT,ERneg,ERpos,62.0,3.0,prechemo tumor size: NA,NaN,3.0,7-Fluorouracil/Doxorubicin/Cyclophosphamide

In [12]:
merg = pd.merge(cd, df, on='patient_ID')

In [13]:
merg.shape

(103, 22295)

In [14]:
merg.to_csv('04_iwamoto_2011_merge.csv')